server:
  port: 80
#---
#spring:
#  profiles: two
#server:
#  port: 80
#---
#---
#spring:
#  profiles: default
#server:
#  port: 80

redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-active: 8
    max-wait: 1
    max-idle: 8
    min-idle: 0
  timeout: 0